#layout: sidebar
layout: stacked
#style: light
style: dark

encoding: utf-8

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  linkedin: "herveleclerc"
  medium: "@herve.leclerc"
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  youtube: "HervéLeclerc-Devops"
  # vk: your_username

topics:
  - name: Docker
    web_url: https://www.docker.com/
    image_url: https://www.docker.com/sites/default/files/social/docker_facebook_share.png

  - name: Kubernetes
    web_url: https://kubernetes.io/
    image_url: https://avatars1.githubusercontent.com/u/13629408?s=400&v=4

  - name: Monitoring
    web_url: https://prometheus.io/
    image_url: https://d15shllkswkct0.cloudfront.net/wp-content/blogs.dir/1/files/2017/11/prometheus_logo.png
